version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.18.2

    steps:
      - checkout
      - run: go get -u github.com/go-bindata/go-bindata/...
      - run: make
      - store_artifacts:
          path: artifacts
